id: P006905
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:29:53.277751
source_metadata:
  id: bdr:W1EE72
  title: གཟུངས་བསྡུས། ༼སོག་ཡིག༽
  author: ''
  volumes:
    cf3448237e07427982f6fcee25bc575c:
      image_group_id: I1KG17008
      title: ''
      volume_number: 1
      total_pages: 499
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
