id: I30B5A08D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T13:58:23+00:00'
last_modified: '2022-06-08T09:30:48.852077+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE72
  title: གཟུངས་བསྡུས། ༼སོག་ཡིག༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    469B:
      image_group_id: I1KG17008
      title: ''
      total_pages: 499
      order: 1
      base_file: 469B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
